-- Create the PROFILES table
CREATE TABLE profiles (
    user_id TEXT PRIMARY KEY,
    total_items_scanned INTEGER DEFAULT 0,
    pending_points INTEGER DEFAULT 0,
    approved_points INTEGER DEFAULT 0
);

-- Create the SCANS_HISTORY table
CREATE TABLE scans_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id TEXT REFERENCES profiles(user_id),
    item_name TEXT,
    category TEXT, -- (Clothing, Footwear, etc.)
    final_decision TEXT,
    points_awarded INTEGER
);

-- Create the LOCATIONS table
CREATE TABLE locations (
    id INTEGER PRIMARY KEY,
    name TEXT,
    address TEXT,
    latitude FLOAT,
    longitude FLOAT
);

-- Create the LOCATION_DEMAND table
CREATE TABLE location_demand (
    location_id INTEGER REFERENCES locations(id),
    category_name TEXT,
    demand_level TEXT, -- e.g., 'High', 'Medium', 'Low'
    PRIMARY KEY (location_id, category_name)
);

--Mock Data--

-- Clear existing data to ensure a clean seed
DELETE FROM location_demand;
DELETE FROM locations;

-- Insert local MD/VA locations with GPS coordinates
INSERT INTO locations (id, name, address, latitude, longitude)
VALUES
(1, 'Goodwill Hyattsville', '4816 Kenilworth Ave, Hyattsville, MD', 38.9482, -76.9324),
(2, 'Goodwill Alexandria', '8228 Richmond Hwy, Alexandria, VA', 38.7455, -77.0892),
(3, 'Goodwill Arlington', '10 South Glebe Rd, Arlington, VA', 38.8655, -77.0885)
ON CONFLICT (id) DO UPDATE SET
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude;

-- Link demand levels to locations
INSERT INTO location_demand (location_id, category_name, demand_level)
VALUES
(1, 'Electronics', 'High'),
(1, 'Clothing', 'Medium'),
(2, 'Furniture', 'High'),
(3, 'Toys & Games', 'High')
ON CONFLICT (location_id, category_name) DO UPDATE SET
  demand_level = EXCLUDED.demand_level;



--Custom Functions

-- Function: Suggest Best Location based on Category Demand
CREATE OR REPLACE FUNCTION suggest_best_location(p_categories TEXT[])
RETURNS TABLE(id INT, name TEXT, address TEXT, latitude FLOAT, longitude FLOAT, matching_categories INT, total_score BIGINT) AS $$
BEGIN
  RETURN QUERY
  SELECT
    l.id,
    l.name,
    l.address,
    l.latitude,
    l.longitude,
    COUNT(d.category_name)::INT AS matching_categories,
    -- Calculate a score based on demand level
    SUM(CASE d.demand_level
          WHEN 'High' THEN 3
          WHEN 'Medium' THEN 2
          WHEN 'Low' THEN 1
          ELSE 0
        END) AS total_score
  FROM locations l
  JOIN location_demand d ON l.id = d.location_id
  WHERE d.category_name = ANY(p_categories)
  GROUP BY l.id, l.name, l.address, l.latitude, l.longitude
  ORDER BY total_score DESC, matching_categories DESC
  LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- Function: Increment Pending Points and Scan Count
CREATE OR REPLACE FUNCTION increment_pending_points(user_id_input TEXT, point_amount INTEGER)
RETURNS void AS $$
BEGIN
  UPDATE profiles
  SET
    pending_points = pending_points + point_amount,
    total_items_scanned = total_items_scanned + 1
  WHERE user_id = user_id_input;
END;
$$ LANGUAGE plpgsql;